import { PrismaClient } from '@prisma/client'
import type { NextPage } from 'next'
import Head from 'next/head'
import { signIn, signOut, useSession } from 'next-auth/react'

import styles from '../styles/Home.module.css'

const Home: NextPage = props => {
  console.log(props?.data)
  const { data: session } = useSession()
  if (session) {
    console.log(session?.user?.email)
    return (
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <button type='submit' onClick={() => signOut()}>
          Signout
        </button>
        <div>
          posts of user are ={' '}
          {props?.data?.map(data => {
            return (
              <>
                sluug: <div>{data.slug}</div>
                userId: <div>{data.userId}</div>
              </>
            )
          })}
        </div>
      </div>
    )
  }
  return (
    <>
      Not signed in <br />
      <button type='submit' onClick={() => signIn()}>
        Sign in
      </button>
    </>
  )
}

export default Home

export const getServerSideProps = async context => {
  const prisma = new PrismaClient()
  const Authuser = await prisma.session?.findFirst({}).user().Blog()
  if (Authuser === null) {
    return {
      props: {}
    }
  }
  return {
    props: {
      data: Authuser?.map(x => {
        x.createdAt = Math.floor(x.createdAt / 1000)
        x.updatedAt = Math.floor(x.updatedAt / 1000)
        return x
      })
    } // will be passed to the page component as props
  }
}
